# Generated by Django 4.2.9 on 2024-03-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_car"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=50)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Pop", "Pop"),
                            ("Rock", "Rock"),
                            ("Hip Hop", "Hip Hop"),
                            ("Electronic", "Electronic"),
                        ],
                        max_length=10,
                    ),
                ),
                ("duration", models.FloatField()),
            ],
        ),
    ]
